import ButtonScrollUpProvider from '@/components/ButtonScrollUpProvider'
import './globals.css'
import type { Metadata } from 'next'
import { Inter,Dancing_Script,Charm,WindSong,Cormorant_Garamond  } from 'next/font/google'
import NavbarProvider from '@/components/NavbarProvider'

const inter = Inter({ subsets: ['latin'] })
const dancing = WindSong({ 
  weight:['400','500'],
  subsets:["latin"],
  variable:"--font-dancing",
})
const charm = Cormorant_Garamond({ 
  subsets:["latin"],
  weight:['400','700'],
  variable:"--font-charm",
})

export const metadata: Metadata = {
  title: 'alamipohotography',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={` ${charm.variable} ${dancing.variable}`}>
        <div className='text-gray-700'>
          <ButtonScrollUpProvider>
            <NavbarProvider>
            {children}
            </NavbarProvider>
          </ButtonScrollUpProvider>
        </div>
      </body>
    </html>
  )
}
