import './globals.css'
import type { Metadata } from 'next'
import { Inter,Dancing_Script,Charm } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })
const dancing = Dancing_Script({ 
  subsets: ['latin'] ,
  variable:"--font-dancing",
})
const charm = Charm({ 
  subsets:["latin"],
  weight:['400','700'],
  variable:"--font-charm",
})

export const metadata: Metadata = {
  title: 'alamipohotography',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={` ${charm.variable} ${dancing.variable}`}>
        <div className='text-gray-700'>
          {children}
        </div>
      </body>
    </html>
  )
}
