import ButtonScrollUpProvider from '@/components/ButtonScrollUpProvider'
import './globals.css'
import type { Metadata } from 'next'
import { Inter,Dancing_Script,Charm,WindSong,Cormorant_Garamond  } from 'next/font/google'
import NavbarProvider from '@/components/NavbarProvider'
import {NextIntlClientProvider} from 'next-intl';
import {notFound} from 'next/navigation';

const inter = Inter({ subsets: ['latin'] })
const dancing = WindSong({ 
  weight:['400','500'],
  subsets:["latin"],
  variable:"--font-dancing",
})
const charm = Cormorant_Garamond({ 
  subsets:["latin"],
  weight:['400','700'],
  variable:"--font-charm",
})
export function generateStaticParams() {
  return [{locale: 'en'}, {locale: 'fr'}];
}
export const metadata: Metadata = {
  title: 'alamipohotography',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
  params:{locale}
}: {
  children: React.ReactNode,
  params:{locale:string}
}) {
  let messages;
  try {
    messages = (await import(`../../messages/${locale}.json`)).default;
  } catch (error) {
    notFound();
  }
  return (
    <html lang={locale}>
      <head>
      <link rel="icon" type="image/png" sizes="32x32" href="/images/favicon.png"/>
      </head>
      <body className={` ${charm.variable} ${dancing.variable}`}>
        <NextIntlClientProvider messages={messages} locale={locale}>

        <div className='text-gray-700'>
          <ButtonScrollUpProvider>
            <NavbarProvider>
            {children}
            </NavbarProvider>
          </ButtonScrollUpProvider>
        </div>

        </NextIntlClientProvider>
      </body>
    </html>
  )
}
